# Generated by Django 3.1.7 on 2021-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0007_auto_20210227_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verbose_id',
            field=models.CharField(default=' ', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
