# Generated by Django 3.1.7 on 2021-03-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0009_auto_20210302_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='verbose_id',
        ),
    ]
