# Generated by Django 3.1.7 on 2021-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_order_verbose_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(default=' ', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
